[package]
name = "nexlint-lints"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = "1.0.52"
camino = "1.0.3"
diffy = "0.3"
globset = "0.4.6"
guppy = "0.15.0"
nexlint = { path = "../nexlint" }
regex = "1.4.3"
serde = { version = "1.0.124", features = ["derive"] }
toml = "0.5.8"
