[package]
name = "nexlint-lints"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = "1.0.104"
camino = "1.2.5"
diffy = "0.4"
globset = "0.4.20"
guppy = "0.17.26"
nexlint = { path = "../nexlint" }
regex = "1.11.1"
serde = { version = "1.0.229", features = ["derive"] }
toml = "0.9.12"
