[package]
name = "nexlint-lints"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = "1.0.86"
camino = "1.1.7"
diffy = "0.3"
globset = "0.4.14"
guppy = "0.17.5"
nexlint = { path = "../nexlint" }
regex = "1.10.4"
serde = { version = "1.0.202", features = ["derive"] }
toml = "0.5.8"
